# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!
target 'xhub' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for xhub
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'

  target 'xhubTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
